export const COMPANY_NAME = 'شركة ربزان التجارية';

export const NAV_LINKS = [
  { name: 'nav.home', path: '/' },
  { name: 'nav.services', path: '/services' },
  { name: 'nav.products', path: '/products' },
  { name: 'nav.portfolio', path: '/portfolio' },
  { name: 'nav.howItWorks', path: '/how-it-works' },
  { name: 'nav.about', path: '/about' },
  { name: 'nav.contact', path: '/contact' },
];

export const SERVICES = [
  {
    id: 'sourcing',
    title: 'services.sourcing.title',
    description: 'services.sourcing.description',
    icon: 'search-check',
  },
  {
    id: 'inspection',
    title: 'services.inspection.title',
    description: 'services.inspection.description',
    icon: 'clipboard-check',
  },
  {
    id: 'logistics',
    title: 'services.logistics.title',
    description: 'services.logistics.description',
    icon: 'ship',
  },
  {
    id: 'customs',
    title: 'services.customs.title',
    description: 'services.customs.description',
    icon: 'file-text',
  },
  {
    id: 'consulting',
    title: 'services.consulting.title',
    description: 'services.consulting.description',
    icon: 'briefcase',
  },
];

export const PROCESS_STEPS = [
  {
    id: 1,
    title: 'process.step1.title',
    description: 'process.step1.description',
  },
  {
    id: 2,
    title: 'process.step2.title',
    description: 'process.step2.description',
  },
  {
    id: 3,
    title: 'process.step3.title',
    description: 'process.step3.description',
  },
  {
    id: 4,
    title: 'process.step4.title',
    description: 'process.step4.description',
  },
  {
    id: 5,
    title: 'process.step5.title',
    description: 'process.step5.description',
  },
];

export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    title: 'portfolio.project1.title',
    category: 'portfolio.project1.category',
    image:
      'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&w=400&q=80',
    description: 'portfolio.project1.description',
  },
  {
    id: 2,
    title: 'portfolio.project2.title',
    category: 'portfolio.project2.category',
    image:
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80',
    description: 'portfolio.project2.description',
  },
  {
    id: 3,
    title: 'portfolio.project3.title',
    category: 'portfolio.project3.category',
    image:
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=400&q=80',
    description: 'portfolio.project3.description',
  },
];

/** خدمات تجارية (كروت + زر اطلب الخدمة → الفورم) */
export const COMMERCIAL_SERVICES = [
  {
    id: 'shipping-clearance',
    title: 'services.commercial.shipping_clearance.title',
    description: 'services.commercial.shipping_clearance.description',
    image:
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'factory-visit',
    title: 'services.commercial.factory_visit.title',
    description: 'services.commercial.factory_visit.description',
    image:
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'sourcing',
    title: 'services.commercial.sourcing.title',
    description: 'services.commercial.sourcing.description',
    image:
      'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=800&q=80',
  },
];

/** مقالات وأخبار (كروت صورة + عنوان + مقتطف + زر جميع المقالات) */
export const ARTICLES = [
  {
    id: 1,
    title: 'articles.1.title',
    snippet: 'articles.1.snippet',
    image:
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 2,
    title: 'articles.2.title',
    snippet: 'articles.2.snippet',
    image:
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 3,
    title: 'articles.3.title',
    snippet: 'articles.3.snippet',
    image:
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=600&q=80',
  },
];

/** منتجات مميزة (كروت منتجات + زر شراء عبر واتساب) */
export const PRODUCTS = [
  {
    id: 1,
    name: 'products.items.1.name',
    category: 'products.items.1.category',
    price: 'products.items.1.price',
    image: '/25KG Fully Auto Washer Extractor (High Spin).png',
    description: 'products.items.1.description',
    longDescription: 'products.items.1.long_description',
    features: [
      'products.items.1.features.0',
      'products.items.1.features.1',
      'products.items.1.features.2',
      'products.items.1.features.3',
      'products.items.1.features.4',
    ],
    specs: {
      washing_capacity: 'products.items.1.specs.washing_capacity',
      drum_volume: 'products.items.1.specs.drum_volume',
      drum_size: 'products.items.1.specs.drum_size',
      material: 'products.items.1.specs.material',
      washing_speed: 'products.items.1.specs.washing_speed',
      high_extraction_speed: 'products.items.1.specs.high_extraction_speed',
      voltage: 'products.items.1.specs.voltage',
      motor_power: 'products.items.1.specs.motor_power',
      electric_heating: 'products.items.1.specs.electric_heating',
      dimension: 'products.items.1.specs.dimension',
      weight: 'products.items.1.specs.weight',
    },
  },
  {
    id: 2,
    name: 'products.items.2.name',
    category: 'products.items.2.category',
    price: 'products.items.2.price',
    image: '/50KG Fully Auto Washer Extractor (High Spin).png',
    description: 'products.items.2.description',
    longDescription: 'products.items.2.long_description',
    features: ['products.items.2.features.0', 'products.items.2.features.1'],
    specs: {
      washing_capacity: 'products.items.2.specs.washing_capacity',
      drum_volume: 'products.items.2.specs.drum_volume',
      drum_size: 'products.items.2.specs.drum_size',
      material: 'products.items.2.specs.material',
      washing_speed: 'products.items.2.specs.washing_speed',
      high_extraction_speed: 'products.items.2.specs.high_extraction_speed',
      voltage: 'products.items.2.specs.voltage',
      motor_power: 'products.items.2.specs.motor_power',
      electric_heating: 'products.items.2.specs.electric_heating',
      dimension: 'products.items.2.specs.dimension',
      weight: 'products.items.2.specs.weight',
    },
  },
  {
    id: 3,
    name: 'products.items.3.name',
    category: 'products.items.3.category',
    price: 'products.items.3.price',
    image: '/100KG Fully Auto Washer Extractor (High Spin).png',
    description: 'products.items.3.description',
    longDescription: 'products.items.3.long_description',
    features: ['products.items.3.features.0', 'products.items.3.features.1'],
    specs: {
      washing_capacity: 'products.items.3.specs.washing_capacity',
      drum_volume: 'products.items.3.specs.drum_volume',
      drum_size: 'products.items.3.specs.drum_size',
      material: 'products.items.3.specs.material',
      washing_speed: 'products.items.3.specs.washing_speed',
      high_extraction_speed: 'products.items.3.specs.high_extraction_speed',
      voltage: 'products.items.3.specs.voltage',
      motor_power: 'products.items.3.specs.motor_power',
      steam_consumption: 'products.items.3.specs.steam_consumption',
      dimension: 'products.items.3.specs.dimension',
      weight: 'products.items.3.specs.weight',
    },
  },
  {
    id: 4,
    name: 'products.items.4.name',
    category: 'products.items.4.category',
    price: 'products.items.4.price',
    image: '/25KG Fully Auto Tumble Dryer.png',
    description: 'products.items.4.description',
    longDescription: 'products.items.4.long_description',
    features: [
      'products.items.4.features.0',
      'products.items.4.features.1',
      'products.items.4.features.2',
    ],
    specs: {
      drying_capacity: 'products.items.4.specs.drying_capacity',
      drum_volume: 'products.items.4.specs.drum_volume',
      drum_size: 'products.items.4.specs.drum_size',
      voltage: 'products.items.4.specs.voltage',
      motor_power: 'products.items.4.specs.motor_power',
      fan_motor_power: 'products.items.4.specs.fan_motor_power',
      electric_heating: 'products.items.4.specs.electric_heating',
      exhaust: 'products.items.4.specs.exhaust',
      dimension: 'products.items.4.specs.dimension',
      weight: 'products.items.4.specs.weight',
    },
  },
  {
    id: 5,
    name: 'products.items.5.name',
    category: 'products.items.5.category',
    price: 'products.items.5.price',
    image: '/50KG Fully Auto Tumble Dryer.png',
    description: 'products.items.5.description',
    longDescription: 'products.items.5.long_description',
    features: [
      'products.items.5.features.0',
      'products.items.5.features.1',
      'products.items.5.features.2',
    ],
    specs: {
      drying_capacity: 'products.items.5.specs.drying_capacity',
      drum_volume: 'products.items.5.specs.drum_volume',
      drum_size: 'products.items.5.specs.drum_size',
      voltage: 'products.items.5.specs.voltage',
      motor_power: 'products.items.5.specs.motor_power',
      fan_motor_power: 'products.items.5.specs.fan_motor_power',
      electric_heating: 'products.items.5.specs.electric_heating',
      drying_time: 'products.items.5.specs.drying_time',
      dimension: 'products.items.5.specs.dimension',
      weight: 'products.items.5.specs.weight',
    },
  },
  {
    id: 6,
    name: 'products.items.6.name',
    category: 'products.items.6.category',
    price: 'products.items.6.price',
    image: '/100KG Fully Auto Tumble Dryer.png',
    description: 'products.items.6.description',
    longDescription: 'products.items.6.long_description',
    features: [
      'products.items.6.features.0',
      'products.items.6.features.1',
      'products.items.6.features.2',
    ],
    specs: {
      drying_capacity: 'products.items.6.specs.drying_capacity',
      drum_volume: 'products.items.6.specs.drum_volume',
      drum_size: 'products.items.6.specs.drum_size',
      voltage: 'products.items.6.specs.voltage',
      motor_power: 'products.items.6.specs.motor_power',
      fan_motor_power: 'products.items.6.specs.fan_motor_power',
      steam_consumption: 'products.items.6.specs.steam_consumption',
      drying_time: 'products.items.6.specs.drying_time',
      dimension: 'products.items.6.specs.dimension',
      weight: 'products.items.6.specs.weight',
    },
  },
  {
    id: 7,
    name: 'products.items.7.name',
    category: 'products.items.7.category',
    price: 'products.items.7.price',
    image: '/1 Roller 3300mm Flatwork Ironer (Electric heated).png',
    description: 'products.items.7.description',
    longDescription: 'products.items.7.long_description',
    features: [
      'products.items.7.features.0',
      'products.items.7.features.1',
      'products.items.7.features.2',
    ],
    specs: {
      length_of_roller: 'products.items.7.specs.length_of_roller',
      number_of_roller: 'products.items.7.specs.number_of_roller',
      cylinder_diameter: 'products.items.7.specs.cylinder_diameter',
      wall_thickness: 'products.items.7.specs.wall_thickness',
      cylinder_material: 'products.items.7.specs.cylinder_material',
      ironing_speed: 'products.items.7.specs.ironing_speed',
      voltage: 'products.items.7.specs.voltage',
      motor_power: 'products.items.7.specs.motor_power',
      electric_heating: 'products.items.7.specs.electric_heating',
      dimension: 'products.items.7.specs.dimension',
      weight: 'products.items.7.specs.weight',
    },
  },
  {
    id: 8,
    name: 'products.items.8.name',
    category: 'products.items.8.category',
    price: 'products.items.8.price',
    image: '/2 Rollers 3300mm Flatwork Ironer (Steam heating).png',
    description: 'products.items.8.description',
    longDescription: 'products.items.8.long_description',
    features: ['products.items.8.features.0', 'products.items.8.features.1'],
    specs: {
      length_of_roller: 'products.items.8.specs.length_of_roller',
      number_of_roller: 'products.items.8.specs.number_of_roller',
      cylinder_diameter: 'products.items.8.specs.cylinder_diameter',
      material: 'products.items.8.specs.material',
      ironing_speed: 'products.items.8.specs.ironing_speed',
      voltage: 'products.items.8.specs.voltage',
      motor_power: 'products.items.8.specs.motor_power',
      steam_consumption: 'products.items.8.specs.steam_consumption',
      dimension: 'products.items.8.specs.dimension',
      weight: 'products.items.8.specs.weight',
    },
  },
  {
    id: 9,
    name: 'products.items.9.name',
    category: 'products.items.9.category',
    price: 'products.items.9.price',
    image: '/4 Lanes 3300mm Fast Speed Bedsheets Folder.png',
    description: 'products.items.9.description',
    longDescription: 'products.items.9.long_description',
    features: [
      'products.items.9.features.0',
      'products.items.9.features.1',
      'products.items.9.features.2',
      'products.items.9.features.3',
    ],
    specs: {
      folding_width: 'products.items.9.specs.folding_width',
      most_folding_levels: 'products.items.9.specs.most_folding_levels',
      inlet_pipe_diameter: 'products.items.9.specs.inlet_pipe_diameter',
      inlet_lowest_pressure: 'products.items.9.specs.inlet_lowest_pressure',
      air_consumption: 'products.items.9.specs.air_consumption',
      voltage: 'products.items.9.specs.voltage',
      motor_power: 'products.items.9.specs.motor_power',
      maximum_folding_speed: 'products.items.9.specs.maximum_folding_speed',
      dimension: 'products.items.9.specs.dimension',
      weight: 'products.items.9.specs.weight',
    },
  },
  {
    id: 10,
    name: 'products.items.10.name',
    category: 'products.items.10.category',
    price: 'products.items.10.price',
    priceIncludesPercent18: true,
    image: '/Disposable Meat Slicer (RBZ-DR350).png',
    gallery: ['/Disposable Meat Slicer (RBZ-DR350) 2.png'],
    description: 'products.items.10.description',
    longDescription: 'products.items.10.long_description',
    features: [
      'products.items.10.features.0',
      'products.items.10.features.1',
      'products.items.10.features.2',
    ],
    specs: {
      model: 'products.items.10.specs.model',
      material: 'products.items.10.specs.material',
      production_capacity: 'products.items.10.specs.production_capacity',
      cutting_size: 'products.items.10.specs.cutting_size',
      cutting_groove_size: 'products.items.10.specs.cutting_groove_size',
      oil_pump_motor: 'products.items.10.specs.oil_pump_motor',
      reducer_motor: 'products.items.10.specs.reducer_motor',
      voltage: 'products.items.10.specs.voltage',
      dimension: 'products.items.10.specs.dimension',
      weight: 'products.items.10.specs.weight',
    },
  },
  {
    id: 11,
    name: 'products.items.11.name',
    category: 'products.items.11.category',
    price: 'products.items.11.price',
    priceIncludesPercent18: true,
    image: '/Hair Stick Peeling Machine (Model: RBZ -MG1800).png',
    gallery: ['/Hair Stick Peeling Machine (Model: RBZ -MG1800)2.png'],
    description: 'products.items.11.description',
    longDescription: 'products.items.11.long_description',
    features: [
      'products.items.11.features.0',
      'products.items.11.features.1',
      'products.items.11.features.2',
    ],
    specs: {
      model: 'products.items.11.specs.model',
      material: 'products.items.11.specs.material',
      production_capacity: 'products.items.11.specs.production_capacity',
      number_of_roller: 'products.items.11.specs.number_of_roller',
      length_of_roller: 'products.items.11.specs.length_of_roller',
      cylinder_diameter: 'products.items.11.specs.cylinder_diameter',
      motor_power: 'products.items.11.specs.motor_power',
      voltage: 'products.items.11.specs.voltage',
      dimension: 'products.items.11.specs.dimension',
      weight: 'products.items.11.specs.weight',
    },
  },
  {
    id: 12,
    name: 'products.items.12.name',
    category: 'products.items.12.category',
    price: 'products.items.12.price',
    priceIncludesPercent18: true,
    image: '/Meat Pie Machine (Model: RBZ -MB100).png',
    gallery: ['/Meat Pie Machine (Model: RBZ -MB100)2.png'],
    description: 'products.items.12.description',
    longDescription: 'products.items.12.long_description',
    features: [
      'products.items.12.features.0',
      'products.items.12.features.1',
      'products.items.12.features.2',
    ],
    specs: {
      model: 'products.items.12.specs.model',
      material: 'products.items.12.specs.material',
      voltage: 'products.items.12.specs.voltage',
      motor_power: 'products.items.12.specs.motor_power',
      production_rate: 'products.items.12.specs.production_rate',
      bucket_capacity: 'products.items.12.specs.bucket_capacity',
      conveyor_width: 'products.items.12.specs.conveyor_width',
      conveyor_length: 'products.items.12.specs.conveyor_length',
      product_diameter: 'products.items.12.specs.product_diameter',
      weight: 'products.items.12.specs.weight',
      packing_weight: 'products.items.12.specs.packing_weight',
    },
  },
  {
    id: 13,
    name: 'products.items.13.name',
    category: 'products.items.13.category',
    price: 'products.items.13.price',
    priceIncludesPercent18: true,
    image: '/Bubble Ozone Cleaning Machine (Model: RBZ -QX2200).png',
    gallery: ['/Bubble Ozone Cleaning Machine (Model: RBZ -QX2200)2.png'],
    description: 'products.items.13.description',
    longDescription: 'products.items.13.long_description',
    features: [
      'products.items.13.features.0',
      'products.items.13.features.1',
      'products.items.13.features.2',
    ],
    specs: {
      model: 'products.items.13.specs.model',
      material: 'products.items.13.specs.material',
      voltage: 'products.items.13.specs.voltage',
      motor_power: 'products.items.13.specs.motor_power',
      dimension: 'products.items.13.specs.dimension',
      weight: 'products.items.13.specs.weight',
      production_capacity: 'products.items.13.specs.production_capacity',
    },
  },
  {
    id: 14,
    name: 'products.items.14.name',
    category: 'products.items.14.category',
    price: 'products.items.14.price',
    priceIncludesPercent18: true,
    image: '/Frozen Meat Cutting Machine (Model: RBZ -SR120S).png',
    gallery: ['/Frozen Meat Cutting Machine (Model: RBZ -SR120S)2.png'],
    description: 'products.items.14.description',
    longDescription: 'products.items.14.long_description',
    features: [
      'products.items.14.features.0',
      'products.items.14.features.1',
      'products.items.14.features.2',
    ],
    specs: {
      model: 'products.items.14.specs.model',
      material: 'products.items.14.specs.material',
      cutting_thickness: 'products.items.14.specs.cutting_thickness',
      voltage: 'products.items.14.specs.voltage',
      motor_power: 'products.items.14.specs.motor_power',
      belt_width: 'products.items.14.specs.belt_width',
      cutting_height: 'products.items.14.specs.cutting_height',
      inlet_height: 'products.items.14.specs.inlet_height',
      weight: 'products.items.14.specs.weight',
    },
  },
  {
    id: 15,
    name: 'products.items.15.name',
    category: 'products.items.15.category',
    price: 'products.items.15.price',
    priceIncludesPercent18: true,
    image: '/Cold Laminator (Model: RBZ 1700-B5).png',
    description: 'products.items.15.description',
    longDescription: 'products.items.15.long_description',
    features: [
      'products.items.15.features.0',
      'products.items.15.features.1',
      'products.items.15.features.2',
    ],
    specs: {
      model: 'products.items.15.specs.model',
      machine_type: 'products.items.15.specs.machine_type',
      max_width: 'products.items.15.specs.max_width',
      max_thickness: 'products.items.15.specs.max_thickness',
      laminating_speed: 'products.items.15.specs.laminating_speed',
      motor_power: 'products.items.15.specs.motor_power',
      weight: 'products.items.15.specs.weight',
    },
  },
  {
    id: 16,
    name: 'products.items.16.name',
    category: 'products.items.16.category',
    price: 'products.items.16.price',
    priceIncludesPercent18: true,
    image: '/Eco Solvent Printer MODEL : RBZ-1800.png',
    description: 'products.items.16.description',
    longDescription: 'products.items.16.long_description',
    features: [
      'products.items.16.features.0',
      'products.items.16.features.1',
      'products.items.16.features.2',
    ],
    specs: {
      factory_model: 'products.items.16.specs.factory_model',
      marketing_model: 'products.items.16.specs.marketing_model',
      print_width: 'products.items.16.specs.print_width',
      print_heads: 'products.items.16.specs.print_heads',
      software: 'products.items.16.specs.software',
      package_weight: 'products.items.16.specs.package_weight',
    },
  },
  {
    id: 17,
    name: 'products.items.17.name',
    category: 'products.items.17.category',
    price: 'products.items.17.price_card',
    priceDetailLines: [
      'products.items.17.price_no_cutter',
      'products.items.17.price_with_cutter',
    ],
    priceIncludesPercent18: true,
    image: '/Roll Laminator (1.7m) – Model: RBZ -1700S.png',
    description: 'products.items.17.description',
    longDescription: 'products.items.17.long_description',
    features: [
      'products.items.17.features.0',
      'products.items.17.features.1',
      'products.items.17.features.2',
    ],
    specs: {
      model: 'products.items.17.specs.model',
      max_laminating_width: 'products.items.17.specs.max_laminating_width',
      max_laminating_thickness: 'products.items.17.specs.max_laminating_thickness',
      max_temperature: 'products.items.17.specs.max_temperature',
      max_speed: 'products.items.17.specs.max_speed',
      heating_type: 'products.items.17.specs.heating_type',
      packing_size: 'products.items.17.specs.packing_size',
      package_weight: 'products.items.17.specs.package_weight',
    },
  },
  {
    id: 18,
    name: 'products.items.18.name',
    category: 'products.items.18.category',
    price: 'products.items.18.price',
    priceIncludesPercent18: true,
    image: '/Cutting Plotter (1.6m) – Model: RBZ -GH1660.png',
    description: 'products.items.18.description',
    longDescription: 'products.items.18.long_description',
    features: [
      'products.items.18.features.0',
      'products.items.18.features.1',
      'products.items.18.features.2',
    ],
    specs: {
      model: 'products.items.18.specs.model',
      machine_type: 'products.items.18.specs.machine_type',
      max_material_width: 'products.items.18.specs.max_material_width',
      max_cutting_width: 'products.items.18.specs.max_cutting_width',
      software: 'products.items.18.specs.software',
      packing_size: 'products.items.18.specs.packing_size',
      package_weight: 'products.items.18.specs.package_weight',
    },
  },
];

export const CONTACT_INFO = {
  email: 'Sales@rabzan.com',
  phone: '+8618427306347',
  address:
    'Office 601, Sanrong Building No 47.Luyuan Road Yuexiu District, Guangzhou, China',
  whatsapp: '8618427306347',
  socials: [
    { name: 'contact.socials.linkedin', url: '#', icon: 'linkedin' },
    { name: 'contact.socials.twitter', url: '#', icon: 'twitter' },
    { name: 'contact.socials.instagram', url: '#', icon: 'instagram' },
  ],
};
